trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  imgContainerRegistry: 'cleverpine-docker-registry'
  imgRepository: 'alivolut-platform-ui'
  imgDockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  imgTag: '$(Build.BuildNumber)'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'cleverpine-docker-registry'
    repository: '$(imgRepository)'
    command: 'buildAndPush'
    Dockerfile: '$(imgDockerfilePath)'
    tags: '$(imgTag)'
